const TOGGLE_ALWAYS_CHECK_FOR_ERRORS = 'TOGGLE_ALWAYS_CHECK_FOR_ERRORS';
const TOGGLE_AUTOMATICALLY_UPDATE_NOTES = 'TOGGLE_AUTOMATICALLY_UPDATE_NOTES';
const TOGGLE_HELP_MENU = 'TOGGLE_HELP_MENU';
const TOGGLE_SETTINGS_MENU = 'TOGGLE_SETTINGS_MENU';
const TOGGLE_INPUT = 'TOGGLE_INPUT';

export default {
    TOGGLE_ALWAYS_CHECK_FOR_ERRORS,
    TOGGLE_AUTOMATICALLY_UPDATE_NOTES,
    TOGGLE_HELP_MENU,
    TOGGLE_SETTINGS_MENU,
    TOGGLE_INPUT
};
