const CHECK_FOR_ERRORS = 'CHECK_FOR_ERRORS';
const CHECK_IF_SOLVED = 'CHECK_IF_SOLVED';
const CLEAR_ACTIVE_TILE_INDEX = 'CLEAR_ACTIVE_TILE_INDEX';
const CLEAR_ACTIVE_TILE_NOTE = 'CLEAR_ACTIVE_TILE_NOTE';
const CLEAR_ACTIVE_TILE_VALUE = 'CLEAR_ACTIVE_TILE_VALUE';
const FETCH_BOARD = 'FETCH_BOARD';
const FETCH_BOARD_FAILURE = 'FETCH_BOARD_FAILURE';
const FETCH_BOARD_SUCCESS = 'FETCH_BOARD_SUCCESS';
const REMOVE_FROM_ACTIVE_TILE = 'REMOVE_FROM_ACTIVE_TILE';
const RESET_BOARD = 'RESET_BOARD';
const SET_ACTIVE_TILE_INDEX = 'SET_ACTIVE_TILE_INDEX';
const SET_ACTIVE_TILE_NOTE = 'SET_ACTIVE_TILE_NOTE';
const SET_ACTIVE_TILE_VALUE = 'SET_ACTIVE_TILE_VALUE';
const SOLVE = 'SOLVE';
const TOGGLE_IS_EDITING_NOTES = 'TOGGLE_IS_EDITING_NOTES';
const UPDATE_ACTIVE_TILE = 'UPDATE_ACTIVE_TILE';

export default {
    CHECK_FOR_ERRORS,
    CHECK_IF_SOLVED,
    CLEAR_ACTIVE_TILE_INDEX,
    CLEAR_ACTIVE_TILE_NOTE,
    CLEAR_ACTIVE_TILE_VALUE,
    FETCH_BOARD,
    FETCH_BOARD_FAILURE,
    FETCH_BOARD_SUCCESS,
    REMOVE_FROM_ACTIVE_TILE,
    RESET_BOARD,
    SET_ACTIVE_TILE_INDEX,
    SET_ACTIVE_TILE_NOTE,
    SET_ACTIVE_TILE_VALUE,
    SOLVE,
    TOGGLE_IS_EDITING_NOTES,
    UPDATE_ACTIVE_TILE
};
